# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5be6164aeb064c53e6ccda8bd232596e979d897d7c3badf2da7ba23db5b046fddcb584aff35063fa4447affd73d5699e7ac0b2646f4cc0093cfcf37a9c54dc68

test:
  secret_key_base: 5bfbb090d923f7e3be4d005cde74b02d87ead723d97d96d81da5bdfa71c4e9875c4d67c59eee787aab2359906c46ca7380cfdf275992cf825b125cfc35324b43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
